### ISSUE TITLE
Support local 

### ISSUE THREAD

**Issue by AdelineDs** [randex/material-ui-multiple-dates-picker#2]
Bonjour,

quand peut-on espérer le support des locals avec moment.js ?

L'insertion de la local de moment créer un bug dans mon application, les dates sont décalées...

Merci

**Comment by randex** [comment]
Sorry to let you know, but this package is deprecated and won't be supported. Please use [@ambiot/material-ui-multiple-dates-picker](https://github.com/ambiot-llc/react-mui-multiple-datepicker). Check out readme for more info about the deprecation.
