### ISSUE TITLE
Selected Dates appear one day before the selected dates 

### ISSUE THREAD

**Issue by amirrezafahimi** [randex/material-ui-multiple-dates-picker#6]
let me explain, 
I'm using dates selector to select multiple dates, passing them into react redux to be a part of my state, 
but the dates are wrong
<img width="311" alt="image" src="https://user-images.githubusercontent.com/30985889/156433921-94a10f17-2a2b-4be3-ba0d-9b696daa9f62.png">

here I'm selecting March 9, 10, 11 and the react redux state is 
<img width="159" alt="image" src="https://user-images.githubusercontent.com/30985889/156434069-c9fc0b8b-7dbf-437d-afdc-634dadf820d5.png">

I have to manually add one day to each one to achieve the correct dates.

**Comment by randex** [comment]
Sorry to let you know, but this package is deprecated and won't be supported. Please use [@ambiot/material-ui-multiple-dates-picker](https://github.com/ambiot-llc/react-mui-multiple-datepicker). Check out readme for more info about the deprecation.
