### ISSUE TITLE
Doesn't work with MUI v5

### ISSUE THREAD

**Issue by maxrosenb** [randex/material-ui-multiple-dates-picker#7]
crashes immediately on load when migrating to v5

**Comment by pwetherbee** [comment]
Second this, I ran into the error "cannot read property of null (reading 'down')"

**Comment by maxrosenb** [comment]
yep same error here

**Comment by sgarchavada** [comment]
@pwetherbee  @maxrosenb  Any solution or any alternative for this one.

**Comment by randex** [comment]
Sorry to let you know, but this package is deprecated and won't be supported. Please use [@ambiot/material-ui-multiple-dates-picker](https://github.com/ambiot-llc/react-mui-multiple-datepicker). Check out readme for more info about the deprecation.
