### ISSUE TITLE
Migrate to MUI

### ISSUE THREAD

**Issue by meilechwieder** [randex/material-ui-multiple-dates-picker#9]
Change dependencies from `@material-ui` to `@mui`

**Comment by HunteRoi** [comment]
Hey there! I am trying to use this with MUI too. Did you find a solution or a fork that is up-to-date by any chance? @meilechwieder

**Comment by meilechwieder** [comment]
No I’m waiting for the maintainer to do it

**Comment by randex** [comment]
Sorry to let you know, but this package is deprecated and won't be supported. Please use [@ambiot/material-ui-multiple-dates-picker](https://github.com/ambiot-llc/react-mui-multiple-datepicker). Check out readme for more info about the deprecation.
